## Colors configuration
[colors.primary]
## background = "#181e25"
background = "#1b212d"
foreground = "#ABB2BF"

[colors.normal]

black   = "#32363D"
red     = "#bf5956"
#green   = "#6cc976"
green   = "#55b6c2"
yellow  = "#d3b172"
blue    = "#62AEEF"
magenta = "#c16094"
cyan    = "#62a4d6"
#cyan    = "#569ca3"
white   = "#ABB2BF"

[colors.bright]
black   = "#50545B"
red     = "#EA757E"
green   = "#A2CD83"
yellow  = "#EFCA84"
blue    = "#6CB8F9"
magenta = "#D282E7"
cyan    = "#5FC0CC"
white   = "#B5BCC9"
