# Window rules
#windowrulev2 = tile, class:.* 
# windowrulev = suppressevent maximize, class:.* # Ignore maximize requests from apps. 
# windowrulev = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0 # Fix some dragging issues with XWayland

# General float
windowrule = float on, match:class ^(nemo)$
windowrule = float on, match:class ^(zoom)$
windowrule = float on, match:class ^(galculator)$
windowrule = float on, match:class ^(org.gnome.Calculator)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(miktex-pdftex)$
windowrule = float on, match:class ^(miktex-makefmt)$
windowrule = float on, match:class ^(miktex-mf)$
windowrule = float on, match:class ^(viewnior)$
windowrule = float on, match:class ^(mirage)$
windowrule = float on, match:class ^(xfce-polkit)$
windowrule = float on, match:class ^(org.matplotlib.Matplotlib3)$

# size
windowrule = size 50% 50%, match:class ^(nemo)$

# Emacs org capture
windowrule = float on,     match:title ^(\*\*Capture\*\*)$
windowrule = center on,    match:title ^(\*\*Capture\*\*)$
windowrule = size monitor_w*0.5 monitor_h*0.5, match:title ^(\*\*Capture\*\*)$

# Emacs org agenda
windowrule = float on, match:title ^(\*\*Agenda\*\*)$
windowrule = center on, match:title ^(\*\*Agenda\*\*)$
windowrule = size monitor_w*0.5 monitor_h*0.7, match:title ^(\*\*Agenda\*\*)$

# Persistent workspaces
workspace = 1, monitor:eDP-1, persistent:true, default
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1, persistent:true
workspace = 5, monitor:eDP-1, persistent:true
workspace = 6, monitor:eDP-1, persistent:true
workspace = 7, monitor:eDP-1, persistent:true
workspace = 8, monitor:eDP-1, persistent:true
