[colors.primary]
background = "#221f35"
foreground = "#e1cdf4"

[colors.normal]
black   = "#11111b"
red     = "#e45649"
green   = "#23c436"
yellow  = "#e5cb22"
blue    = "#3aa2e8"
magenta = "#b479f7"
cyan    = "#00c1bc"
white   = "#cdd6f4"

[colors.bright]
black   = "#181825"
red     = "#fca1a4"
green   = "#acdb99"
yellow  = "#fce449"
blue    = "#c0dded"
magenta = "#c69fea"
cyan    = "#4ae0db"
white   = "#dee4f7"
